### ISSUE TITLE
lora_emb in src/finetuning/lora.py

### ISSUE THREAD

**Issue by billakosrizeakos** [automl/automated-sub-network-selection#1]
Hi,

I am trying to replicate your paper's process with the early code you have available.
There is an issue when calling run_calibration.py, where you include the embedding layers as a LoRA trainable parameter, as written in src/finetuning/lora.y

```
    config = Config.from_file(
        checkpoint_dir / "model_config.yaml",
        lora_r=lora_r,
        lora_alpha=lora_alpha,
        lora_dropout=lora_dropout,
        lora_query=lora_query,
        lora_key=lora_key,
        lora_value=lora_value,
        lora_projection=lora_projection,
        lora_mlp=lora_mlp,
        lora_head=lora_head,
        lora_emb=lora_emb,
    )
```

Config is a class from litgpt, but it does not contain that parameter in the source code. 

```
@dataclass
class Config(BaseConfig):
    """
    Args:
        lora_r: rank of the weight update matrices. To make sense of using LoRA the rank should be smaller than the rank of
            the weights of the model. The rank can be as low as 1: https://arxiv.org/pdf/2106.09685.pdf (section 7.2)
        lora_alpha: alpha is needed for scaling updates as alpha/r
            "This scaling helps to reduce the need to retune hyperparameters when we vary r"
            https://arxiv.org/pdf/2106.09685.pdf (section 4.1)
        lora_dropout: dropout that is applied on the input in the LoRA branch (before multiplying by matrix A)
        lora_*: whether to apply LoRA to the specified weights or not
    """

    lora_r: int = 0
    lora_alpha: int = 1
    lora_dropout: float = 0.0
    lora_query: bool = False
    lora_key: bool = False
    lora_value: bool = False
    lora_projection: bool = False
    lora_mlp: bool = False
    lora_head: bool = False
```

Have you included lora_emb in the class' definition or is there something else at play?
